url = uri @@ 0.0;
uri = scheme '://' opt_login host opt_port opt_path opt_query opt_frag opt_ws @@ 0.0;
scheme = string @@ 0.0;
host = '/' host_core @@ 0.0 | host_core @@ 0.0;
host_core = hostname @@ 0.0 | hostnumber @@ 0.0;
hostname = string @@ 0.0 | string '.' string @@ 0.0 | string '.' string '.' string @@ 0.0 | string '.' string '.' string '.' string @@ 0.0;
hostnumber = DIGITS '.' DIGITS '.' DIGITS '.' DIGITS @@ 0.0;
port = DIGITS @@ 0.0;
path = string @@ 0.0 | string '/' string @@ 0.0 | string '/' string '/' string @@ 0.0 | string '/' string '/' string '/' string @@ 0.0;
user = string @@ 0.0;
login = user ':' password '@' @@ 0.0;
password = string @@ 0.0;
frag = '#' string @@ 0.0;
query = '?' search @@ 0.0;
search = searchparameter @@ 0.0 | searchparameter '&' searchparameter @@ 0.0 | searchparameter '&' searchparameter '&' searchparameter @@ 0.0 | searchparameter '&' searchparameter '&' searchparameter '&' searchparameter @@ 0.0;
searchparameter = string @@ 0.0 | string '=' string @@ 0.0 | string '=' DIGITS @@ 0.0 | string '=' HEX @@ 0.0;
opt_login = login @@ 0.0 | "" @@ 0.0;
opt_port = ':' port @@ 0.0 | "" @@ 0.0;
opt_path = '/' path @@ 0.0 | "" @@ 0.0;
opt_query = query @@ 0.0 | "" @@ 0.0;
opt_frag = frag @@ 0.0 | "" @@ 0.0;
opt_ws = WS @@ 0.0 | "" @@ 0.0;
DIGITS = /[0-9]/+ @@ 0.0;
HEX = /(%[a-fA-F0-9][a-fA-F0-9])/+ @@ 0.0;
string = /[a-zA-Z~0-9]/ stringtail @@ 0.0 | HEX stringtail @@ 0.0;
stringtail = "" @@ 0.0; | tail_unit @@ 0.0; | tail_unit tail_unit @@ 0.0; | tail_unit tail_unit tail_unit @@ 0.0;
tail_unit = /[a-zA-Z0-9.-]/ @@ 0.0 | HEX @@ 0.0;
WS = /[\\r\\n]/+ @@ 0.0;
